version: '3'
services:
  db:
    image: postgres:11.19-alpine
    container_name: db_pms
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD='postgres'
      - DB_USERNAME='postgres'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:alpine
    env_file:
      - .env
    command: redis-server
    volumes:
      - .:/app
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - default

  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3003:3000
    depends_on:
      - db
      - redis
    networks:
      - default
